### ISSUE TITLE
Will preparation – build free online tool for Veterans

### ISSUE THREAD

**Issue by JeffL-T** [TechForJustice/project-ideas#25]
The US Dept of Veteran Affairs provides a no-cost online will preparation service for beneficiaries of certain servicemember and veterans group life insurance plans in order “to quickly and easily prepare a will without an attorney.  After answering a series of straightforward questions, the beneficiary will receive a legal will, valid in all states, ready to print and sign.”  

The service is handled by FinancialPointPlus.com, and requires an 8-digit insurance claim number to access the service.  However, claim numbers are not issued until the servicemember or veteran dies.  Effectively, the veteran’s death unlocks the VA benefit for their beneficiaries upon death, but the benefit is not available for veterans themselves, nor their beneficiaries while the veterans are living.   

Prudential, who is behind the financial Point Plus.com, confirmed that the benefit is available for beneficiaries after the veterans death, but the benefit is not available to service members or veterans.  

VA link: http://www.benefits.va.gov/insurance/bfcs.asp

**Comment by christyleos** [comment]
What solution are you proposing?

**Comment by JeffL-T** [comment]
I propose to build a tool that produces a printable legal will, similar to the services of existing online will services, that can be then downloaded, witnessed or notarized in accordance with state law.

**Comment by hlholmes** [comment]
Possibly helpful as a model? 
https://farewill.com/
This is designed for the UK, but could serve as a jumping off place.

**Comment by christyleos** [comment]
Other possible model: https://www.doyourownwill.com/

**Comment by christyleos** [comment]
@JeffL-T why close this?

**Comment by JeffL-T** [comment]
Embarrassingly, by mistake.

Can you re-open, or do I need to?

**Comment by rgranat** [comment]
The VA site is only for beneficiaries but should be open to Veterans as JeffL-T points out. We have already built a free Wills site for a major insurance company (MetLIfe) and we can repurpose part of the code for this project- see: http://www.willscenter.com You can register and test out the functionality of this site. This site already has state specific Wills, Powers of Attorney and Living Wills, so it pretty advanced. The particular piece of code that we want to build for this hackathon- and open source it,  is an interactive checklist so that veterans can determine what estate planning documents they need.. Jeff do you want to join our team?

**Comment by christyleos** [comment]
Closing and moving conversation to #39

**Comment by rgranat** [comment]
JeffL-T's idea for a document generator for Wills is an idea that would provide a valuable service to Veterans -- but it is technology and legal content that has already been developed and in place. 
We have been generating Wills directly to consumers from the Web for over 5 years. See for example: http://www.willscenter.com .  I don;t consider this to be an innovative idea at this point.

There are two issues that need resolution. 
The first issue is how do you effectively authenticate Veterans during registration so that you don't get free riders. If you have a genuinely free Wills service for Veterans on the Web you want to make sure that non-Veterans don't take advantage of it.  
The second issue is even more important: how do you engage veterans in understanding that the lack of estate planning documents can create real problems and that they can be solved with a simple legal solution. Becky Sandifer's research shows (see attachments) that most low/moderate income clients don't really understand that they have a legal problem. Even the cost of lawyers is not so much as a problem as lack of engagement. See papers attached. 
Our (one) solution, for now is an Estate Planning Interactive Checkup - but I think we need to brain storm other ideas that increase engagement and gets the attention of veterans.  We need engagement tools and smart marketing to get this problem in front of veterans so that they can get this problem solved.

The "attention" problem is much greater than anyone thinks. The technology exists and even lawyer costs are not that high -- but getting veterans to do something about estate planning is a low priority for them.

See ABA Grant Award to Legal services Committee to deal with this Attention Problem.

[legal_checkup_issues_paper_final_3_march 22.pdf](https://github.com/TechForJustice/project-ideas/files/841255/legal_checkup_issues_paper_final_3_march.22.pdf)
[Enterprise-Fund-Application_legal-check-ups..pdf](https://github.com/TechForJustice/project-ideas/files/841266/Enterprise-Fund-Application_legal-check-ups.pdf)
